[uwsgi]
http-socket = :9090
my_app_folder = /home/hshallal/dona

chdir = %(my_app_folder)
socket = %(my_app_folder)/dona.sock
chmod-socket = 777
uid = hshallal
gid = www-data
vacuum = true

wsgi-file = dona.py
callable = dona
venv = /home/hshallal/dona/deploy

processes = 1
disable-logging = True
